### ISSUE TITLE
State of project

### ISSUE THREAD

**Issue by etsinko** [johnnyletrois/monoprice6z#1]
Hi what is the state of this project. Is it in working condition?

Egor

**Comment by johnnyletrois** [comment]
Someone else already created a custom media_player component for the Monoprice controller.  See my experience here: https://community.home-assistant.io/t/monoprice-whole-home-audio-controller-10761-success/19734

It works great!

**Comment by etsinko** [comment]
Thanks for the info! 
I see it requires a Node server running. I wonder if it will ever be accepted into Home Asistant.

**Comment by johnnyletrois** [comment]
I don't know but using it as a custom_component works well even after updates.
